#!/bin/bash

#SBATCH --job-name=cbir             # Job name
#SBATCH --output=logs/cbir_%j.out # Name of output file
#SBATCH --cpus-per-task=9          # Schedule one core
#SBATCH --time=06:00:00            # Run time (hh:mm:ss)
#SBATCH --partition=red            # Run on either the Red or Brown queue
#SBATCH --mem=128000               # memory

module load Python/3.9.6-GCCcore-11.2.0

source venv/bin/activate

python main.py
